### ISSUE TITLE
"fishing intensity" used incorrectly

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#158]
The SPR-based default harvest control rule is confusing but we have no choice about that.
We've defined "fishing intensity" as "A measure of the magnitude of fishing relative to a specified target." and specifically (1-SPR) / (1 - SPR_40%).

Therefore, in the "FORECAST DECISION TABLES" section, it's not right to say "Decision tables give the projected population status (relative spawning biomass) and the fishing intensity (1-SPR40%) relative to target fishing intensity, under different catch alternatives...." Since Fishing Intensity is accurately defined in the table caption, I would simply revise to say ""Decision tables give the projected population status (relative spawning biomass) and the fishing intensity under different catch alternatives...."

In the "Exploitation Status" section it says "Median fishing intensity on the stock is estimated to have been below the F_SPR=40% target except for the years 2008 and 2010...." Again, the target fishing intensity is 100%, not F_SPR=40%, so I would just delete the F_SPR=40% and have it say "...below the target...."

I can make these changes myself but wanted to allow you all to suggest something different first.

**Comment by allanhicks** [comment]
I agree that we should make some simple changes this year, as Ian has
suggested.

However, for the future, I wonder if (1-SPR)/(1-SPR_40%) should be defined
as relative fishing intensity and (1-SPR) be defined as fishing intensity.
Then SPR could still be SPR.  Just a suggestion to think about for next
year.

**Comment by andrew-edwards** [comment]
So I just copied what was written last year, and never really got my head around it all. Chris and I plan to understand it more for next year, when we'll have more time. 
So, yes, make the changes. Also check the Glossary, and please edit if necessary.

**Comment by taylori** [comment]
Sounds good. I'll make the changes later today. I think the glossary is
good for now, we just need to make the language consistent with it. I like
Allan's idea for next year, maybe I'll use my new "2017 assessment"
milestone to post an issue for us to deal with next time.

**Comment by taylori** [comment]
I just made a commit to fix this but it's behind the @andrew-edwards fork.
I'm not sure how to sort this out myself, so I'm trusting that Andy can sort this out. If there's something I need to do, let me know.

**Comment by andrew-edwards** [comment]
I took a quick look and doubt it will conflict with any of the other commits, so a merge in the morning should work fine (I'm not on my work computer right now, else I'd just do it).

Looks like you made changes in Exec Summary and main text, so everything should be consistent, yes? Chris and I will try and understand this stuff better next year, especially as we shouldn't have to focus on the formatting aspects.....

**Comment by taylori** [comment]
Yes, I changed Exec Summary and main text and I believe things are now
consistent. I also added a comment in the appendix to remind us to refer to
this issue thread next year.

**Comment by cgrandin** [comment]
Git is very flexible - if you make changes to your own fork, it shows up on the network graph of everyone else who has a fork. When you look at the network graph, if there are names below yours, you do not have their changes yet. If someone merges with someone else, the graph will change so that only the person's name who merged appears (because now they have everything from everyone else). If it's only your name on the graph, you are fully up-to-date. The graph is like a to-do list, where you merge the names of all those appearing into yours to be up-to-date. The best thing is that it doesn't matter who merges with who, it will all be solved by Git.

**Comment by andrew-edwards** [comment]
Just ran a spell check on the latest commit - a474...   Looks good. I suspect Hiedelberger on p25 should be Heidelberger (like the town in Germany!) but didn't change it. Looks like Chris has been spotting a few minor things, but I'm thinking we can get submitted soon??

**Comment by taylori** [comment]
Yes, definitely Heidelberger and Welch. Indeed, our draft 2016 assessment
is in the top 10 hits for the mispelled version:
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Hiedelberger+and+Welch&nfpr=1

I'm OK with you submitting whenever those of you more involved than me are
happy with the document. Allan is out to lunch (literally) but should be
back soon to chime in on timing and any remaining tasks.

-Ian

**Comment by andrew-edwards** [comment]
Fixed Heidelberger.

**Comment by kellijohnson-NOAA** [comment]
This issue is still noted in the executive summary Management Performance section
https://github.com/pacific-hake/hake-assessment/blob/a31c161a11a15dfea506af6b39f023f488cd9115/doc/executive-summary/executive-summary.rnw#L503
I am unsure if we can just remove the comment or if this should be re-opened.
